Add XUnit
iisuslik43/javaHW2 pull request #8
Opened 2018-05-19 14:30 UTC by iisuslik43

2018-06-04 09:31 UTC, jzuken requested changes

2018-06-04 09:31 UTC, jzuken commented on XUnit/src/main/java/ru/iisuslik/xunit/XUnit.java
> +  private void addMethodsToLists(Class<?> testClass) {
было бы здорово также проверить, что на один метод не повесили больше одной аннотации. и тесты на это написать

2018-06-15 18:27 UTC, iisuslik43 commented on XUnit/src/main/java/ru/iisuslik/xunit/XUnit.java
> +  private void addMethodsToLists(Class<?> testClass) {
Если в методе будет 2 одинаковые аннотации, то класс не скомпилируется в .class файл, компилятор скажет, что у аннотации нет аннотации Repeatable, а мой XUnit работает на уже готовых .class файлах.

2018-06-20 07:11 UTC, jzuken commented on XUnit/src/main/java/ru/iisuslik/xunit/XUnit.java
> +  private void addMethodsToLists(Class<?> testClass) {
я про то, что не навесили @Before и @Test, например

2018-06-20 07:11 UTC, jzuken commented on XUnit/src/main/java/ru/iisuslik/xunit/XUnit.java
> +  private void addMethodsToLists(Class<?> testClass) {
я про то, что не навесили @Before и @Test, например

2018-06-20 09:29 UTC, merged